### ISSUE TITLE
GPL 3 vs. MIT

### ISSUE THREAD

**Issue by peterennis** [notoriousb1t/polymorph#14]
@delucis/filesize-cli is a dependency of polymorph i.e.
GPL 3 vs. MIT

Maybe it should be fixed so that copyleft does not come into play?

![capture369](https://user-images.githubusercontent.com/140737/47396797-24e87580-d6e1-11e8-97ba-62bc2eba46c8.PNG)

![capture370](https://user-images.githubusercontent.com/140737/47396799-29149300-d6e1-11e8-816d-b264eeac7f21.PNG)

**Comment by peterennis** [comment]
I do not know how @delucis/filesize-cli is being used with polymorph so this may be a non issue.

**Comment by notoriousb1t** [comment]
I don't see this as being a conflict because filesize-cli isn't being used on any of the source code or output of the library.  That being said, I am not a fan of using GPL because it imposes artificial limitations on how opensource software can be used. I very much prefer Apache 2.0 or MIT because they are friendly to commercial uses and because the language accurate describes the rights of the author and the way it is licensed to be used.  

Looking through the source, I think filesize is a left over artifact from an earlier version.  I'm not able to update this easily at the moment for certain reasons, but I would gladly take a PR to remove it if you feel so inclined.

**Comment by peterennis** [comment]
OK. I pan to look more through the code and can do this at the same time.

**Comment by peterennis** [comment]
@notoriousb1t 
Confirmed no evidence of GPL3 in 0.2.4 on npm
