### ISSUE TITLE
Webpack grabbing es2015 version instead – fails to run on older browser

### ISSUE THREAD

**Issue by ericbf** [notoriousb1t/polymorph#40]
Hello!

I'm trying to import this into a project that supports only up to es5 (to support ie11 🤷🏻‍♂️) but it is throwing errors because it pulls in the es2015 version of the lib.

Is there a way to pull in an es5 compatible version, or to transpile a version to es5?

**Comment by ericbf** [comment]
I'm trying to install through `npm`

**Comment by notoriousb1t** [comment]
That is strange. The package.json on the current published version is set to the lib/index.js version for the main file and that is the ES5 version. If you are using Webpack, you could alias the dist/polymorph.min.js file as a global directly from your npm installation and that would provide an ES5 version. 

As an aside,I have considered dropping the es2015 version entirely because sometimes the builders choose the wrong one.

**Comment by ericbf** [comment]
Yeah – we're using webpack. For some reason it chooses the es2015 instead of the es5 version. I'll try an override. What's the benefit of having the es2015 compiled version at all over not just es5?

**Comment by ericbf** [comment]
Seems it uses the module reference `"module": "./lib.es2015/index.js",` because it grabs the lib.es2015 version.
